package views;

import java.awt.Color;
import static java.lang.Float.parseFloat;
import java.sql.ResultSet;
import java.sql.SQLException;

import database.providerDB;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author axdevil
 */
public class newProduct extends javax.swing.JPanel {

    /**
     * Creates new form newProduct
     */
    public newProduct() {
        initComponents();
        try {
            fillProvider(providerDB.get());
        } catch (SQLException ex) {
            Logger.getLogger(newProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codeTitle = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        descriptionTitle = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        priceTitle = new javax.swing.JLabel();
        price = new javax.swing.JFormattedTextField();
        MXN = new javax.swing.JLabel();
        wholesalePriceTitle = new javax.swing.JLabel();
        wholesalePrice = new javax.swing.JFormattedTextField();
        MXN1 = new javax.swing.JLabel();
        gainTitle = new javax.swing.JLabel();
        gain = new javax.swing.JFormattedTextField();
        MXN2 = new javax.swing.JLabel();
        providerTitle = new javax.swing.JLabel();
        provider = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        codeTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        codeTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        codeTitle.setText("* Codigo:");

        code.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        descriptionTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        descriptionTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descriptionTitle.setText("Descripcion:");

        description.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        priceTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        priceTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        priceTitle.setText("* Precio:");

        price.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        price.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        price.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                priceCaretUpdate(evt);
            }
        });

        MXN.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MXN.setText("MXN");

        wholesalePriceTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        wholesalePriceTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        wholesalePriceTitle.setText("Precio mayoreo:");

        wholesalePrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        wholesalePrice.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        wholesalePrice.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                wholesalePriceCaretUpdate(evt);
            }
        });

        MXN1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MXN1.setText("MXN");

        gainTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gainTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gainTitle.setText("Ganancia:");

        gain.setEditable(false);
        gain.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        gain.setEnabled(false);
        gain.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        gain.setVerifyInputWhenFocusTarget(false);

        MXN2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        MXN2.setText("MXN");

        providerTitle.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        providerTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        providerTitle.setText("Proveedor:");
        providerTitle.setToolTipText("");

        provider.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        save.setBackground(new java.awt.Color(41, 121, 255));
        save.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descriptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wholesalePriceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(providerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(provider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MXN))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(gain, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(wholesalePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MXN1)
                                            .addComponent(MXN2)))
                                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(code)
                    .addComponent(codeTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MXN, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wholesalePriceTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(wholesalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MXN1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MXN2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save)
                    .addComponent(cancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wholesalePriceCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_wholesalePriceCaretUpdate
        getGain();
    }//GEN-LAST:event_wholesalePriceCaretUpdate

    private void priceCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_priceCaretUpdate
        getGain();
    }//GEN-LAST:event_priceCaretUpdate

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    private void getGain(){
        if(wholesalePrice.getText().length() > 0){
            try{
                float r = parseFloat(price.getValue().toString()) - parseFloat(wholesalePrice.getValue().toString());
                gain.setText(Float.toString(r));
                if(r >= 0){
                    gainTitle.setForeground(codeTitle.getForeground());
                }else{
                    gainTitle.setForeground(new Color(255,68,41));
                }
            }catch(Exception e){}
        }else{
            gain.setText("");
        }
    }
    
    private void fillProvider(ResultSet query) throws SQLException{
        provider.removeAllItems();
        
        while(query.next()){
            provider.addItem(query.getString("id") + " " + query.getString("name") + " " + query.getString("appat") + " " + query.getString("apmat"));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MXN;
    private javax.swing.JLabel MXN1;
    private javax.swing.JLabel MXN2;
    private javax.swing.JButton cancel;
    public javax.swing.JTextField code;
    private javax.swing.JLabel codeTitle;
    private javax.swing.JTextField description;
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JFormattedTextField gain;
    private javax.swing.JLabel gainTitle;
    private javax.swing.JFormattedTextField price;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JComboBox<String> provider;
    private javax.swing.JLabel providerTitle;
    private javax.swing.JButton save;
    private javax.swing.JFormattedTextField wholesalePrice;
    private javax.swing.JLabel wholesalePriceTitle;
    // End of variables declaration//GEN-END:variables
}
