package views;

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import database.providerDB;
import salecat.global;
/**
 *
 * @author axdevil
 */
public class provider extends javax.swing.JPanel {

    /**
     * Creates new form providerDB
     */
    public provider() {
        initComponents();
        
        setVisibleButtons(false);
        
        try {
            fillTable(providerDB.get());
        } catch (SQLException ex) {
            Logger.getLogger(providerDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableScroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        create = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        remove = new javax.swing.JButton();

        table.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido paterno", "Apellido materno", "Empresa", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tableFocusGained(evt);
            }
        });
        tableScroll.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMaxWidth(32);
        }

        create.setBackground(new java.awt.Color(41, 121, 255));
        create.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Nuevo");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        edit.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        edit.setText("Editar");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        remove.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        remove.setText("Eliminar");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tableScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(remove)
                    .addComponent(edit))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        newProvider w = new newProvider(0,0);
        
        menu.changeContent(w, "Nuevo proveedor", w.name);
    }//GEN-LAST:event_createActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        String[] buttons = {"No","Si"};
        int option = JOptionPane.showOptionDialog(null, "¿Seguro que quieres eliminar a " + global.getDataTable((DefaultTableModel) table.getModel(), table, 1) + "?","Confirmacion",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, buttons, buttons[1]);
        
        if(option == 1){
            try{
                providerDB.delete(global.getDataTable((DefaultTableModel) table.getModel(), table, 0));
                fillTable(providerDB.get());
            }catch(SQLException e){
                Logger.getLogger(providerDB.class.getName()).log(Level.SEVERE, null, e);
            }
        }else{
            return;
        }
    }//GEN-LAST:event_removeActionPerformed

    private void tableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tableFocusGained
        setVisibleButtons(true);
    }//GEN-LAST:event_tableFocusGained

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        newProvider w = new newProvider(1, Integer.parseInt(global.getDataTable((DefaultTableModel) table.getModel(), table, 0)));
        
        menu.changeContent(w, "Editar proveedor", w.name);
    }//GEN-LAST:event_editActionPerformed
    
    public static void fillTable(ResultSet query) throws SQLException{
        String[] data = new String[6];
        
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        
        while(query.next()){
            data[0] = query.getString("id");
            data[1] = query.getString("name");
            data[2] = query.getString("appat");
            data[3] = query.getString("apmat");
            data[4] = query.getString("business");
            data[5] = query.getString("phone");
            model.addRow(data);
        }
        table.setModel(model);
    }
    
    private void setVisibleButtons(boolean visible){
        edit.setVisible(visible);
        remove.setVisible(visible);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton edit;
    private javax.swing.JButton remove;
    private static javax.swing.JTable table;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
