package views;

import java.sql.ResultSet;

import database.userDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import salecat.global;
/**
 *
 * @author jorge garcia
 */
public class settings extends javax.swing.JPanel {

    /**
     * Creates new form settings
     */
    public settings() {
        initComponents();
        
        try {
            ResultSet userName = userDB.getNameById(global.getActualUser());
            while(userName.next()){
                actualUser.setText("Usuario actual: " + userName.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actualUser = new javax.swing.JLabel();

        actualUser.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        actualUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualUser.setText("Usuario actual: 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(actualUser, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(actualUser)
                .addContainerGap(69, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actualUser;
    // End of variables declaration//GEN-END:variables
}
