package views;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import salecat.printer;
/**
 *
 * @author axdevil
 */
public class ticket extends javax.swing.JPanel {

    /**
     * Creates new form ticket
     */
    public ticket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentTicketScroll = new javax.swing.JScrollPane();
        contentTicket = new javax.swing.JTextArea();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        test = new javax.swing.JButton();

        setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        contentTicket.setColumns(1);
        contentTicket.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        contentTicket.setLineWrap(true);
        contentTicket.setRows(5);
        contentTicket.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        contentTicketScroll.setViewportView(contentTicket);

        save.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        save.setText("Guardar");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cancel.setText("Cancelar");

        test.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        test.setText("Prueba");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(contentTicketScroll)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel)
                        .addGap(16, 16, 16)
                        .addComponent(test)
                        .addGap(16, 16, 16)
                        .addComponent(save)))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(contentTicketScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancel)
                        .addComponent(test)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        
    }//GEN-LAST:event_saveActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        try {
            printer.printTicket(contentTicket.getText());
        } catch (IOException ex) {
            Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_testActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextArea contentTicket;
    private javax.swing.JScrollPane contentTicketScroll;
    private javax.swing.JButton save;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables
}
